code:
- Data/Scripts/**/*.cs

doc:
- doc/**/*.md
- README.md

automation:
- .github/**/*
- .gitignore
- .gitattribute

ship:
- Data/Prefabs/*.sbc

model:
- Models/**/*.*

textures:
- Textures/**/*.*

sandbox-definition:
- Data/*.sbc

audio:
 - Sounds/**/*.*

audio:
 - Sounds/**/*.*

license:
- LICENSE
