code:
- Data/Scripts/**/*.cs

doc:
- doc/**/*.md
- README.md

automation:
- .github/**/*
- .gitignore
- .gitattribute

definitions:
- any: ['Data/**/*.sbc', '!Data/Encounters/Prefabs/*', '!Data/Encounters/Behaviors/*']

ship:
- Data/Encounters/Prefabs/*.sbc

behavior:
- Data/Encounters/Behaviors/*.sbc

license:
- LICENSE
